use_frameworks!

target 'ELComboBox_Example', :exclusive => true do
  pod 'ELComboBox', :path => '../'
end

target 'ELComboBox_Tests', :exclusive => true do
  pod 'ELComboBox', :path => '../'

  
end
